In [99]:
import numpy as np
import pandas as pd
import nose.tools as nt
import seaborn as sns
import matplotlib.pyplot as plt

from selectinf.base import (full_targets,
                     selected_targets,
                     debiased_targets)

from selectinf.randomized.group_lasso_query import (group_lasso,
                                                    split_group_lasso)

# Data Cleaning

In [3]:
data_raw = pd.read_csv("data_groups_dummy_encoded.csv")

In [6]:
data_raw

SEQN  depressed  RIDAGEYR  INDFMPIR  BMXBMI  DBD895  DBD905  DBD910  \
0     109273          1        36      0.83    21.9       2       0       7   
1     109274          0        68      1.20    30.2       0       0       0   
2     109282          0        76      3.61    26.6       1       1       8   
3     109292          0        58      1.60    30.5       2      10       3   
4     109293          0        44      0.02    30.1       3       7       0   
...      ...        ...       ...       ...     ...     ...     ...     ...   
5980  124814          0        64      2.00    37.5       3       1       2   
5981  124815          0        52      5.00    29.5       1       0       0   
5982  124817          0        67      2.19    37.9       4       0       0   
5983  124818          0        40      3.82    38.2       4       5       0   
5984  124821          0        63      3.71    25.5       0       0       0   

      RIDRETH1_Mexican_American  RIDRETH1_Other_Hispanic  ...  RIAGENDR_man  \
0                             0                        0  ...             1   
1                             0                        0  ...             1   
2                             0                        0  ...             1   
3                             0                        1  ...             1   
4                             0                        0  ...             1   
...                         ...                      ...  ...           ...   
5980                          0                        0  ...             1   
5981                          0                        0  ...             1   
5982                          1                        0  ...             0   
5983                          0                        0  ...             1   
5984                          0                        0  ...             1   

      DMDBORN4_US  ALQ111_dummy  ALQ151_dummy  BPQ020_hypertension  \
0               1             1             0                    0   
1               1             1             0                    1   
2               1             1             0                    1   
3               1             1             0                    1   
4               1             1             1                    0   
...           ...           ...           ...                  ...   
5980            1             1             0                    0   
5981            1             1             0                    0   
5982            0             1             0                    0   
5983            1             1             0                    0   
5984            1             1             0                    1   

      BPQ080_high_cholesterol  SMQ020_smoke  MCQ010_asthma  MCQ053_anemia  \
0                           0             1              0              0   
1                           1             0              0              0   
2                           1             1              0              1   
3                           1             0              1              0   
4                           0             0              0              0   
...                       ...           ...            ...            ...   
5980                        0             1              0              0   
5981                        0             1              0              0   
5982                        1             0              0              0   
5983                        0             0              0              0   
5984                        1             0              1              0   

      MCQ092_blood_transfusion  
0                            0  
1                            0  
2                            0  
3                            0  
4                            0  
...                        ...  
5980                         0  
5981                         0  
5982                         0  
5983          

In [38]:
DBQ197 = data_raw[["DBQ197_never","DBQ197_often",
        "DBQ197_rarely", "DBQ197_sometimes"]].to_numpy()

In [42]:
(data_raw["ALQ111_dummy"] != 1).sum()

0

In [52]:
data_X = data_raw[data_raw.columns[2:50]].drop(columns="ALQ111_dummy")

In [54]:
data_X.columns

Index(['RIDAGEYR', 'INDFMPIR', 'BMXBMI', 'DBD895', 'DBD905', 'DBD910',
       'RIDRETH1_Mexican_American', 'RIDRETH1_Other_Hispanic',
       'RIDRETH1_Non_Hispanic_White', 'RIDRETH1_Non_Hispanic_Black',
       'DMDEDUC2_1', 'DMDEDUC2_2', 'DMDEDUC2_3', 'DMDEDUC2_4',
       'DMDMARTZ_married_living_with', 'DMDMARTZ_sep', 'INDFMMPC_1',
       'INDFMMPC_2', 'ALQ121_0', 'ALQ121_1', 'ALQ121_2', 'ALQ121_3',
       'ALQ121_4', 'ALQ121_5', 'ALQ121_6', 'ALQ121_7', 'ALQ121_8', 'ALQ121_9',
       'DBQ700_1', 'DBQ700_2', 'DBQ700_3', 'DBQ700_4', 'DBQ197_never',
       'DBQ197_rarely', 'DBQ197_sometimes', 'DBQ197_often', 'DIQ010_diabetes',
       'DIQ010_diabetes_borderline', 'RIAGENDR_man', 'DMDBORN4_US',
       'ALQ151_dummy', 'BPQ020_hypertension', 'BPQ080_high_cholesterol',
       'SMQ020_smoke', 'MCQ010_asthma', 'MCQ053_anemia',
       'MCQ092_blood_transfusion'],
      dtype='object')

In [55]:
data_X = data_X.to_numpy()

In [56]:
np.linalg.matrix_rank(data_X)

47

In [57]:
data_X.shape

(5985, 47)

In [58]:
design_X = np.zeros((5985,48))
design_X[:,0] = np.ones((5985,))
design_X[:,1:48] = data_X

In [59]:
np.linalg.matrix_rank(design_X)

48

In [60]:
design_X.shape

(5985, 48)

In [61]:
design_X

array([[ 1.  , 36.  ,  0.83, ...,  0.  ,  0.  ,  0.  ],
       [ 1.  , 68.  ,  1.2 , ...,  0.  ,  0.  ,  0.  ],
       [ 1.  , 76.  ,  3.61, ...,  0.  ,  1.  ,  0.  ],
       ...,
       [ 1.  , 67.  ,  2.19, ...,  0.  ,  0.  ,  0.  ],
       [ 1.  , 40.  ,  3.82, ...,  0.  ,  0.  ,  0.  ],
       [ 1.  , 63.  ,  3.71, ...,  1.  ,  0.  ,  0.  ]])

# Construct Groups

In [67]:
data_raw[data_raw.columns[2:50]].drop(columns="ALQ111_dummy").columns

Index(['RIDAGEYR', 'INDFMPIR', 'BMXBMI', 'DBD895', 'DBD905', 'DBD910',
       'RIDRETH1_Mexican_American', 'RIDRETH1_Other_Hispanic',
       'RIDRETH1_Non_Hispanic_White', 'RIDRETH1_Non_Hispanic_Black',
       'DMDEDUC2_1', 'DMDEDUC2_2', 'DMDEDUC2_3', 'DMDEDUC2_4',
       'DMDMARTZ_married_living_with', 'DMDMARTZ_sep', 'INDFMMPC_1',
       'INDFMMPC_2', 'ALQ121_0', 'ALQ121_1', 'ALQ121_2', 'ALQ121_3',
       'ALQ121_4', 'ALQ121_5', 'ALQ121_6', 'ALQ121_7', 'ALQ121_8', 'ALQ121_9',
       'DBQ700_1', 'DBQ700_2', 'DBQ700_3', 'DBQ700_4', 'DBQ197_never',
       'DBQ197_rarely', 'DBQ197_sometimes', 'DBQ197_often', 'DIQ010_diabetes',
       'DIQ010_diabetes_borderline', 'RIAGENDR_man', 'DMDBORN4_US',
       'ALQ151_dummy', 'BPQ020_hypertension', 'BPQ080_high_cholesterol',
       'SMQ020_smoke', 'MCQ010_asthma', 'MCQ053_anemia',
       'MCQ092_blood_transfusion'],
      dtype='object')

In [129]:
groups = np.zeros((48,))
groups[0] = int(0) # Intercept
# Singletons
for i in range(1,7):
    groups[i] = int(i)
# RIDRETH1
groups[7:11] = int(7)
# DMDEDUC2
groups[11:15] = int(8)
# DMDMARTZ
groups[15:17] = int(9)
# INDFMMPC
groups[17:19] = int(10)
# ALQ121
groups[19:29] = int(11)
# DBQ700
groups[29:33] = int(12)
# DBQ197
groups[33:37] = int(13)
# DIQ010
groups[37:39] = int(14)
# Singletons
for i in range(39,48):
    groups[i] = int(i-24)

groups = groups.astype(int)

In [118]:
col_names = data_raw[data_raw.columns[2:50]].drop(columns="ALQ111_dummy").columns.values.tolist()
col_names = ['Intercept'] + col_names

In [151]:
# Sanity check for groupings
pd.DataFrame([groups,col_names])

0         1         2       3       4       5       6   \
0          0         1         2       3       4       5       6   
1  Intercept  RIDAGEYR  INDFMPIR  BMXBMI  DBD895  DBD905  DBD910   

                          7                        8   \
0                          7                        7   
1  RIDRETH1_Mexican_American  RIDRETH1_Other_Hispanic   

                            9   ...                          38            39  \
0                            7  ...                          14            15   
1  RIDRETH1_Non_Hispanic_White  ...  DIQ010_diabetes_borderline  RIAGENDR_man   

            40            41                   42                       43  \
0           16            17                   18                       19   
1  DMDBORN4_US  ALQ151_dummy  BPQ020_hypertension  BPQ080_high_cholesterol   

             44             45             46                        47  
0            20             21             22                        23  
1  SMQ020_smoke  MCQ010_asthma  MCQ053_anemia  MCQ092_blood_transfusion  

[2 rows x 48 columns]

In [144]:
n,p = design_X.shape
scaling_cts = np.ones((p,))
scaling_cts[1:7] = design_X.std(0)[1:7]
cts_logical = np.zeros((p,))
cts_logical[1:7] = 1.

In [146]:
print(np.linalg.matrix_rank(design_X))
scaling = design_X.std(0) * np.sqrt(n)
scaling[0] = np.sqrt(n)
X_standardized = design_X - (cts_logical * design_X.mean(axis = 0))
print(np.linalg.matrix_rank(X_standardized))
X_standardized = X_standardized / scaling[None, :]
print(np.linalg.matrix_rank(X_standardized))

48
48
48


In [147]:
Y = data_raw["depressed"]
sigma_ = np.std(Y)
weight_frac = 0.5
sigma_ = 1
weights = dict([(i, weight_frac * sigma_ * np.sqrt(2 * np.log(p))) for i in np.unique(groups)])
weights[0] = 0

In [149]:
conv = split_group_lasso.logistic(X=X_standardized,
                                      successes=Y,
                                      trials=np.ones(n),
                                      groups=groups,
                                      weights=weights,
                                      useJacobian=True,
                                      proportion=0.67)
signs, soln = conv.fit()
nonzero = signs != 0

ValueError: shapes (13,22) and (23,23) not aligned: 22 (dim 1) != 23 (dim 0)

In [123]:
conv.setup_inference(dispersion=1)

target_spec = selected_targets(conv.loglike,
                               conv.observed_soln,
                               dispersion=1)

result = conv.inference(target_spec,
                        method='selective_MLE',
                        level=0.9)

pval = result['pvalue']
intervals = np.asarray(result[['lower_confidence',
                               'upper_confidence']])

In [124]:
nonzero

array([False, False,  True,  True, False, False,  True, False, False,
       False, False, False, False, False, False,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False,  True, False,  True, False, False,  True,
        True, False, False])

In [125]:
nonzero.sum()

23

In [126]:
pval

0     0.022754
1     0.940999
2     0.038752
3     0.409326
4     0.336704
5     0.737676
6     0.431419
7     0.972185
8     0.914992
9     0.269062
10    0.486398
11    0.546491
12    0.902279
13    0.944154
14    0.807458
15    0.007525
16    0.003701
17    0.007047
18    0.039266
19    0.029305
20    0.005042
21    0.787656
22    0.006821
Name: pvalue, dtype: float64

In [153]:
conv_iso = group_lasso.logistic(X=X_standardized,
                                      successes=Y,
                                      trials=np.ones(n),
                                      groups=groups,
                                      weights=weights,
                                      useJacobian=True,
                            randomizer_scale=sigma_)
signs_iso, soln_iso = conv_iso.fit()
nonzero_iso = signs_iso != 0

ValueError: shapes (23,37) and (38,38) not aligned: 37 (dim 1) != 38 (dim 0)

In [130]:
groups

array([ 0,  1,  2,  3,  4,  5,  6,  7,  7,  7,  7,  8,  8,  8,  8,  9,  9,
       10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 13,
       13, 13, 13, 14, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [133]:
X_standardized.shape

(5985, 48)

In [134]:
np.linalg.matrix_rank(X_standardized)

47